apiVersion: batch/v1
kind: Job
metadata:
  name: consul-kv-loader
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kv-loader
          image: alpine:3.18
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache jq curl >/dev/null

              echo "⏳ Waiting for Consul to start..."
              until curl -s {{ .Values.consulAddress }}/v1/status/leader | grep -q '"'; do
                sleep 1
              done
              echo "✅ Consul is available. Loading KV-data..."

              for key in $(jq -r 'keys[]' /config/{{ .Values.filename }}); do
                value=$(jq -r --arg key "$key" '.[$key]' /config/{{ .Values.filename }})
                echo "📥 Loading $key = $value"
                curl -s -X PUT --data "$value" {{ .Values.consulAddress }}/v1/kv/$key > /dev/null
              done

              echo "✅ Loading finished"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configMapName }}