version: '3'
services:
  pdf-service-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    container_name: pdf-service-metrics
    ports:
      - "8428:8428"
    volumes:
      - ./config/victoria-metrics/promscrape.yaml:/promscrape.yaml
#      - /Users/sultan/Documents/intellijeIDEA_workspace/My_projects/PdfAsScanned/PdfAsScanned/config/victoria-metrics/promscrape.yaml:/promscrape.yaml

    command:
      - "-promscrape.config=promscrape.yaml"

# docker run --name selmag-metrics -p 8428:8428 -v ./config/victoria-metrics/promscrape.yaml:/promscrape.yaml victoriametrics/victoria-metrics:v1.93.12 -promscrape.config=promscrape.yaml