input {
  kafka {
    bootstrap_servers => "kafka-1:9090,kafka-2:9090,kafka-3:9090"
    topics_pattern     => "^logs-(?<service>.+?)-topic$"
    group_id           => "logstash-group"
    codec              => "json"
    auto_offset_reset  => "latest"
    consumer_threads   => 1
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{DATA:thread}\] %{LOGLEVEL:level}\s+%{JAVACLASS:logger} - %{GREEDYDATA:msg}"
    }
  }

  date {
    match       => [ "timestamp", "yyyy-MM-dd HH:mm:ss.SSS" ]
    target      => "@timestamp"
    timezone    => "+02:00"
  }

  mutate {
    remove_field => [
      "message",
      "event",
      "host",
      "agent",
      "ecs",
      "input",
      "log",
      "timestamp",
      "@metadata",
      "@version"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{service}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
